/*
 * cpu1 pin map for the STM32H743ZITx (LQFP144).
 *
 * GENERATED from hw/cpu1/pinmap.py by hw/tools/mcu_pins.py. Do not edit:
 * a check fails if this file differs from what the pin map generates.
 * Regenerate with `make -C hw pins-write BOARD=cpu1`.
 */
#ifndef CPU1_BOARD_PINS_H
#define CPU1_BOARD_PINS_H

/* SWDIO: DEBUG_JTMS-SWDIO on PA13, pin 105 */
#define PIN_SWDIO_PORT GPIOA
#define PIN_SWDIO_PIN GPIO_PIN_13
#define PIN_SWDIO_AF GPIO_AF0_TRACE

/* SWCLK: DEBUG_JTCK-SWCLK on PA14, pin 109 */
#define PIN_SWCLK_PORT GPIOA
#define PIN_SWCLK_PIN GPIO_PIN_14
#define PIN_SWCLK_AF GPIO_AF0_TRACE

/* SWO: DEBUG_JTDO-SWO on PB3, pin 133 */
#define PIN_SWO_PORT GPIOB
#define PIN_SWO_PIN GPIO_PIN_3
#define PIN_SWO_AF GPIO_AF0_TRACE

/* HSE_IN: RCC_OSC_IN on PH0, pin 23. 8 MHz crystal */
#define PIN_HSE_IN_PORT GPIOH
#define PIN_HSE_IN_PIN GPIO_PIN_0

/* HSE_OUT: RCC_OSC_OUT on PH1, pin 24 */
#define PIN_HSE_OUT_PORT GPIOH
#define PIN_HSE_OUT_PIN GPIO_PIN_1

/* LSE_IN: RCC_OSC32_IN on PC14, pin 8. 32.768 kHz crystal */
#define PIN_LSE_IN_PORT GPIOC
#define PIN_LSE_IN_PIN GPIO_PIN_14

/* LSE_OUT: RCC_OSC32_OUT on PC15, pin 9 */
#define PIN_LSE_OUT_PORT GPIOC
#define PIN_LSE_OUT_PIN GPIO_PIN_15

/* USB_DM: USB_OTG_FS_DM on PA11, pin 103 */
#define PIN_USB_DM_PORT GPIOA
#define PIN_USB_DM_PIN GPIO_PIN_11
#define PIN_USB_DM_AF GPIO_AF10_OTG1_FS

/* USB_DP: USB_OTG_FS_DP on PA12, pin 104 */
#define PIN_USB_DP_PORT GPIOA
#define PIN_USB_DP_PIN GPIO_PIN_12
#define PIN_USB_DP_AF GPIO_AF10_OTG1_FS

/* USB_VBUS: USB_OTG_FS_VBUS on PA9, pin 101. through a divider; USB is not a power input */
#define PIN_USB_VBUS_PORT GPIOA
#define PIN_USB_VBUS_PIN GPIO_PIN_9

/* CAN_RX: FDCAN1_RX on PD0, pin 114 */
#define PIN_CAN_RX_PORT GPIOD
#define PIN_CAN_RX_PIN GPIO_PIN_0
#define PIN_CAN_RX_AF GPIO_AF9_FDCAN1

/* CAN_TX: FDCAN1_TX on PD1, pin 115 */
#define PIN_CAN_TX_PORT GPIOD
#define PIN_CAN_TX_PIN GPIO_PIN_1
#define PIN_CAN_TX_AF GPIO_AF9_FDCAN1

/* CAN_STANDBY: GPIO output on PD3, pin 117 */
#define PIN_CAN_STANDBY_PORT GPIOD
#define PIN_CAN_STANDBY_PIN GPIO_PIN_3

/* ETH_REF_CLK: ETH_REF_CLK on PA1, pin 35. 50 MHz from the PHY */
#define PIN_ETH_REF_CLK_PORT GPIOA
#define PIN_ETH_REF_CLK_PIN GPIO_PIN_1
#define PIN_ETH_REF_CLK_AF GPIO_AF11_ETH

/* ETH_MDIO: ETH_MDIO on PA2, pin 36 */
#define PIN_ETH_MDIO_PORT GPIOA
#define PIN_ETH_MDIO_PIN GPIO_PIN_2
#define PIN_ETH_MDIO_AF GPIO_AF11_ETH

/* ETH_MDC: ETH_MDC on PC1, pin 27 */
#define PIN_ETH_MDC_PORT GPIOC
#define PIN_ETH_MDC_PIN GPIO_PIN_1
#define PIN_ETH_MDC_AF GPIO_AF11_ETH

/* ETH_CRS_DV: ETH_CRS_DV on PA7, pin 43 */
#define PIN_ETH_CRS_DV_PORT GPIOA
#define PIN_ETH_CRS_DV_PIN GPIO_PIN_7
#define PIN_ETH_CRS_DV_AF GPIO_AF11_ETH

/* ETH_RXD0: ETH_RXD0 on PC4, pin 44 */
#define PIN_ETH_RXD0_PORT GPIOC
#define PIN_ETH_RXD0_PIN GPIO_PIN_4
#define PIN_ETH_RXD0_AF GPIO_AF11_ETH

/* ETH_RXD1: ETH_RXD1 on PC5, pin 45 */
#define PIN_ETH_RXD1_PORT GPIOC
#define PIN_ETH_RXD1_PIN GPIO_PIN_5
#define PIN_ETH_RXD1_AF GPIO_AF11_ETH

/* ETH_TX_EN: ETH_TX_EN on PG11, pin 126 */
#define PIN_ETH_TX_EN_PORT GPIOG
#define PIN_ETH_TX_EN_PIN GPIO_PIN_11
#define PIN_ETH_TX_EN_AF GPIO_AF11_ETH

/* ETH_TXD0: ETH_TXD0 on PG13, pin 128 */
#define PIN_ETH_TXD0_PORT GPIOG
#define PIN_ETH_TXD0_PIN GPIO_PIN_13
#define PIN_ETH_TXD0_AF GPIO_AF11_ETH

/* ETH_TXD1: ETH_TXD1 on PG12, pin 127. not PB13 as on the NUCLEO: that is TIM1_CH1N */
#define PIN_ETH_TXD1_PORT GPIOG
#define PIN_ETH_TXD1_PIN GPIO_PIN_12
#define PIN_ETH_TXD1_AF GPIO_AF11_ETH

/* ETH_PHY_RESET: GPIO output on PG15, pin 132 */
#define PIN_ETH_PHY_RESET_PORT GPIOG
#define PIN_ETH_PHY_RESET_PIN GPIO_PIN_15

/* RS485_TX: USART2_TX on PD5, pin 119 */
#define PIN_RS485_TX_PORT GPIOD
#define PIN_RS485_TX_PIN GPIO_PIN_5
#define PIN_RS485_TX_AF GPIO_AF7_USART2

/* RS485_RX: USART2_RX on PD6, pin 122 */
#define PIN_RS485_RX_PORT GPIOD
#define PIN_RS485_RX_PIN GPIO_PIN_6
#define PIN_RS485_RX_AF GPIO_AF7_USART2

/* RS485_DE: USART2_DE on PD4, pin 118. driver enable, timed by the UART itself */
#define PIN_RS485_DE_PORT GPIOD
#define PIN_RS485_DE_PIN GPIO_PIN_4
#define PIN_RS485_DE_AF GPIO_AF7_USART2

/* CONSOLE_TX: USART3_TX on PD8, pin 77. also the ROM bootloader's */
#define PIN_CONSOLE_TX_PORT GPIOD
#define PIN_CONSOLE_TX_PIN GPIO_PIN_8
#define PIN_CONSOLE_TX_AF GPIO_AF7_USART3

/* CONSOLE_RX: USART3_RX on PD9, pin 78 */
#define PIN_CONSOLE_RX_PORT GPIOD
#define PIN_CONSOLE_RX_PIN GPIO_PIN_9
#define PIN_CONSOLE_RX_AF GPIO_AF7_USART3

/* PWM1_A_HIGH: TIM1_CH1 on PE9, pin 60 */
#define PIN_PWM1_A_HIGH_PORT GPIOE
#define PIN_PWM1_A_HIGH_PIN GPIO_PIN_9
#define PIN_PWM1_A_HIGH_AF GPIO_AF1_TIM1

/* PWM1_A_LOW: TIM1_CH1N on PE8, pin 59 */
#define PIN_PWM1_A_LOW_PORT GPIOE
#define PIN_PWM1_A_LOW_PIN GPIO_PIN_8
#define PIN_PWM1_A_LOW_AF GPIO_AF1_TIM1

/* PWM1_B_HIGH: TIM1_CH2 on PE11, pin 64 */
#define PIN_PWM1_B_HIGH_PORT GPIOE
#define PIN_PWM1_B_HIGH_PIN GPIO_PIN_11
#define PIN_PWM1_B_HIGH_AF GPIO_AF1_TIM1

/* PWM1_B_LOW: TIM1_CH2N on PE10, pin 63 */
#define PIN_PWM1_B_LOW_PORT GPIOE
#define PIN_PWM1_B_LOW_PIN GPIO_PIN_10
#define PIN_PWM1_B_LOW_AF GPIO_AF1_TIM1

/* PWM1_C_HIGH: TIM1_CH3 on PE13, pin 66 */
#define PIN_PWM1_C_HIGH_PORT GPIOE
#define PIN_PWM1_C_HIGH_PIN GPIO_PIN_13
#define PIN_PWM1_C_HIGH_AF GPIO_AF1_TIM1

/* PWM1_C_LOW: TIM1_CH3N on PE12, pin 65 */
#define PIN_PWM1_C_LOW_PORT GPIOE
#define PIN_PWM1_C_LOW_PIN GPIO_PIN_12
#define PIN_PWM1_C_LOW_AF GPIO_AF1_TIM1

/* PWM1_CH4: TIM1_CH4 on PE14, pin 67. single-ended: no complementary pair, no dead time */
#define PIN_PWM1_CH4_PORT GPIOE
#define PIN_PWM1_CH4_PIN GPIO_PIN_14
#define PIN_PWM1_CH4_AF GPIO_AF1_TIM1

/* TRIP1_N: TIM1_BKIN on PE15, pin 68. from the hardware trip latch, active low */
#define PIN_TRIP1_N_PORT GPIOE
#define PIN_TRIP1_N_PIN GPIO_PIN_15
#define PIN_TRIP1_N_AF GPIO_AF1_TIM1

/* FAULT1_N: TIM1_BKIN2 on PE6, pin 5. gate-driver fault, active low */
#define PIN_FAULT1_N_PORT GPIOE
#define PIN_FAULT1_N_PIN GPIO_PIN_6
#define PIN_FAULT1_N_AF GPIO_AF1_TIM1

/* PWM2_A_HIGH: TIM8_CH1 on PC6, pin 96 */
#define PIN_PWM2_A_HIGH_PORT GPIOC
#define PIN_PWM2_A_HIGH_PIN GPIO_PIN_6
#define PIN_PWM2_A_HIGH_AF GPIO_AF3_TIM8

/* PWM2_A_LOW: TIM8_CH1N on PA5, pin 41. PA7 is Ethernet's CRS_DV */
#define PIN_PWM2_A_LOW_PORT GPIOA
#define PIN_PWM2_A_LOW_PIN GPIO_PIN_5
#define PIN_PWM2_A_LOW_AF GPIO_AF3_TIM8

/* PWM2_B_HIGH: TIM8_CH2 on PC7, pin 97 */
#define PIN_PWM2_B_HIGH_PORT GPIOC
#define PIN_PWM2_B_HIGH_PIN GPIO_PIN_7
#define PIN_PWM2_B_HIGH_AF GPIO_AF3_TIM8

/* PWM2_B_LOW: TIM8_CH2N on PB14, pin 75 */
#define PIN_PWM2_B_LOW_PORT GPIOB
#define PIN_PWM2_B_LOW_PIN GPIO_PIN_14
#define PIN_PWM2_B_LOW_AF GPIO_AF3_TIM8

/* PWM2_C_HIGH: TIM8_CH3 on PC8, pin 98 */
#define PIN_PWM2_C_HIGH_PORT GPIOC
#define PIN_PWM2_C_HIGH_PIN GPIO_PIN_8
#define PIN_PWM2_C_HIGH_AF GPIO_AF3_TIM8

/* PWM2_C_LOW: TIM8_CH3N on PB15, pin 76 */
#define PIN_PWM2_C_LOW_PORT GPIOB
#define PIN_PWM2_C_LOW_PIN GPIO_PIN_15
#define PIN_PWM2_C_LOW_AF GPIO_AF3_TIM8

/* PWM2_CH4: TIM8_CH4 on PC9, pin 99. single-ended: no complementary pair, no dead time */
#define PIN_PWM2_CH4_PORT GPIOC
#define PIN_PWM2_CH4_PIN GPIO_PIN_9
#define PIN_PWM2_CH4_AF GPIO_AF3_TIM8

/* TRIP2_N: TIM8_BKIN on PG2, pin 87. one latch output, one node, both timers */
#define PIN_TRIP2_N_PORT GPIOG
#define PIN_TRIP2_N_PIN GPIO_PIN_2
#define PIN_TRIP2_N_AF GPIO_AF3_TIM8

/* FAULT2_N: TIM8_BKIN2 on PG3, pin 88. gate-driver fault, active low */
#define PIN_FAULT2_N_PORT GPIOG
#define PIN_FAULT2_N_PIN GPIO_PIN_3
#define PIN_FAULT2_N_AF GPIO_AF3_TIM8

/* FAST1: ADC1_INP2 on PF11, pin 49. simultaneous with FAST2 */
#define PIN_FAST1_PORT GPIOF
#define PIN_FAST1_PIN GPIO_PIN_11
#define PIN_FAST1_ADC ADC1
#define PIN_FAST1_ADC_CHANNEL ADC_CHANNEL_2

/* FAST2: ADC2_INP2 on PF13, pin 53 */
#define PIN_FAST2_PORT GPIOF
#define PIN_FAST2_PIN GPIO_PIN_13
#define PIN_FAST2_ADC ADC2
#define PIN_FAST2_ADC_CHANNEL ADC_CHANNEL_2

/* FAST3: ADC3_INP0 on PC2_C, pin 28. needs the PC2 analog switch closed */
#define PIN_FAST3_PORT GPIOC
#define PIN_FAST3_PIN GPIO_PIN_2
#define PIN_FAST3_ADC ADC3
#define PIN_FAST3_ADC_CHANNEL ADC_CHANNEL_0

/* FAST4: ADC1_INP3 on PA6, pin 42. simultaneous with FAST5 */
#define PIN_FAST4_PORT GPIOA
#define PIN_FAST4_PIN GPIO_PIN_6
#define PIN_FAST4_ADC ADC1
#define PIN_FAST4_ADC_CHANNEL ADC_CHANNEL_3

/* FAST5: ADC2_INP5 on PB1, pin 47 */
#define PIN_FAST5_PORT GPIOB
#define PIN_FAST5_PIN GPIO_PIN_1
#define PIN_FAST5_ADC ADC2
#define PIN_FAST5_ADC_CHANNEL ADC_CHANNEL_5

/* FAST6: ADC3_INP1 on PC3_C, pin 29. needs the PC3 analog switch closed */
#define PIN_FAST6_PORT GPIOC
#define PIN_FAST6_PIN GPIO_PIN_3
#define PIN_FAST6_ADC ADC3
#define PIN_FAST6_ADC_CHANNEL ADC_CHANNEL_1

/* FAST7: ADC3_INP2 on PF9, pin 21 */
#define PIN_FAST7_PORT GPIOF
#define PIN_FAST7_PIN GPIO_PIN_9
#define PIN_FAST7_ADC ADC3
#define PIN_FAST7_ADC_CHANNEL ADC_CHANNEL_2

/* FAST8: ADC3_INP3 on PF7, pin 19 */
#define PIN_FAST8_PORT GPIOF
#define PIN_FAST8_PIN GPIO_PIN_7
#define PIN_FAST8_ADC ADC3
#define PIN_FAST8_ADC_CHANNEL ADC_CHANNEL_3

/* SLOW1: ADC3_INP4 on PF5, pin 15 */
#define PIN_SLOW1_PORT GPIOF
#define PIN_SLOW1_PIN GPIO_PIN_5
#define PIN_SLOW1_ADC ADC3
#define PIN_SLOW1_ADC_CHANNEL ADC_CHANNEL_4

/* SLOW2: ADC3_INP5 on PF3, pin 13 */
#define PIN_SLOW2_PORT GPIOF
#define PIN_SLOW2_PIN GPIO_PIN_3
#define PIN_SLOW2_ADC ADC3
#define PIN_SLOW2_ADC_CHANNEL ADC_CHANNEL_5

/* SLOW3: ADC3_INP10 on PC0, pin 26 */
#define PIN_SLOW3_PORT GPIOC
#define PIN_SLOW3_PIN GPIO_PIN_0
#define PIN_SLOW3_ADC ADC3
#define PIN_SLOW3_ADC_CHANNEL ADC_CHANNEL_10

/* SLOW4: ADC1_INP15 on PA3, pin 37 */
#define PIN_SLOW4_PORT GPIOA
#define PIN_SLOW4_PIN GPIO_PIN_3
#define PIN_SLOW4_ADC ADC1
#define PIN_SLOW4_ADC_CHANNEL ADC_CHANNEL_15

/* BOARD_ID1: ADC3_INP6 on PF10, pin 22. resistor divider on the power board */
#define PIN_BOARD_ID1_PORT GPIOF
#define PIN_BOARD_ID1_PIN GPIO_PIN_10
#define PIN_BOARD_ID1_ADC ADC3
#define PIN_BOARD_ID1_ADC_CHANNEL ADC_CHANNEL_6

/* BOARD_ID2: ADC3_INP9 on PF4, pin 14 */
#define PIN_BOARD_ID2_PORT GPIOF
#define PIN_BOARD_ID2_PIN GPIO_PIN_4
#define PIN_BOARD_ID2_ADC ADC3
#define PIN_BOARD_ID2_ADC_CHANNEL ADC_CHANNEL_9

/* COMP_FAST4: COMP1_INP on PB2, pin 48. optional second over-voltage path */
#define PIN_COMP_FAST4_PORT GPIOB
#define PIN_COMP_FAST4_PIN GPIO_PIN_2

/* DAC_TEST: DAC1_OUT1 on PA4, pin 40. resolver excitation or analog test */
#define PIN_DAC_TEST_PORT GPIOA
#define PIN_DAC_TEST_PIN GPIO_PIN_4

/* ENC_A: TIM4_CH1 on PD12, pin 81 */
#define PIN_ENC_A_PORT GPIOD
#define PIN_ENC_A_PIN GPIO_PIN_12
#define PIN_ENC_A_AF GPIO_AF2_TIM4

/* ENC_B: TIM4_CH2 on PD13, pin 82 */
#define PIN_ENC_B_PORT GPIOD
#define PIN_ENC_B_PIN GPIO_PIN_13
#define PIN_ENC_B_AF GPIO_AF2_TIM4

/* ENC_Z: TIM4_CH3 on PD14, pin 85 */
#define PIN_ENC_Z_PORT GPIOD
#define PIN_ENC_Z_PIN GPIO_PIN_14
#define PIN_ENC_Z_AF GPIO_AF2_TIM4

/* HALL_1: TIM3_CH1 on PB4, pin 134 */
#define PIN_HALL_1_PORT GPIOB
#define PIN_HALL_1_PIN GPIO_PIN_4
#define PIN_HALL_1_AF GPIO_AF2_TIM3

/* HALL_2: TIM3_CH2 on PB5, pin 135 */
#define PIN_HALL_2_PORT GPIOB
#define PIN_HALL_2_PIN GPIO_PIN_5
#define PIN_HALL_2_AF GPIO_AF2_TIM3

/* HALL_3: TIM3_CH3 on PB0, pin 46 */
#define PIN_HALL_3_PORT GPIOB
#define PIN_HALL_3_PIN GPIO_PIN_0
#define PIN_HALL_3_AF GPIO_AF2_TIM3

/* ENC_SERIAL_TX: USART1_TX on PB6, pin 136. reserved: the encoder type is undecided */
#define PIN_ENC_SERIAL_TX_PORT GPIOB
#define PIN_ENC_SERIAL_TX_PIN GPIO_PIN_6
#define PIN_ENC_SERIAL_TX_AF GPIO_AF7_USART1

/* ENC_SERIAL_RX: USART1_RX on PB7, pin 137 */
#define PIN_ENC_SERIAL_RX_PORT GPIOB
#define PIN_ENC_SERIAL_RX_PIN GPIO_PIN_7
#define PIN_ENC_SERIAL_RX_AF GPIO_AF7_USART1

/* PWM_ENABLE_N: GPIO output on PG4, pin 89. pulled up on the board, so off until driven */
#define PIN_PWM_ENABLE_N_PORT GPIOG
#define PIN_PWM_ENABLE_N_PIN GPIO_PIN_4

/* TRIP_CLEAR_N: GPIO output on PG5, pin 90. the only way to clear the trip latch; pulled up, so a reset pin does not clear it */
#define PIN_TRIP_CLEAR_N_PORT GPIOG
#define PIN_TRIP_CLEAR_N_PIN GPIO_PIN_5

/* DAC_SDA: I2C2_SDA on PF0, pin 10. trip-threshold DAC */
#define PIN_DAC_SDA_PORT GPIOF
#define PIN_DAC_SDA_PIN GPIO_PIN_0
#define PIN_DAC_SDA_AF GPIO_AF4_I2C2

/* DAC_SCL: I2C2_SCL on PF1, pin 11 */
#define PIN_DAC_SCL_PORT GPIOF
#define PIN_DAC_SCL_PIN GPIO_PIN_1
#define PIN_DAC_SCL_AF GPIO_AF4_I2C2

/* GATE_ENABLE: GPIO output on PD7, pin 123 */
#define PIN_GATE_ENABLE_PORT GPIOD
#define PIN_GATE_ENABLE_PIN GPIO_PIN_7

/* RELAY1: GPIO output on PG0, pin 56 */
#define PIN_RELAY1_PORT GPIOG
#define PIN_RELAY1_PIN GPIO_PIN_0

/* RELAY2: GPIO output on PG1, pin 57 */
#define PIN_RELAY2_PORT GPIOG
#define PIN_RELAY2_PIN GPIO_PIN_1

/* STO1_FEEDBACK: GPIO input on PG9, pin 124 */
#define PIN_STO1_FEEDBACK_PORT GPIOG
#define PIN_STO1_FEEDBACK_PIN GPIO_PIN_9

/* STO2_FEEDBACK: GPIO input on PG10, pin 125 */
#define PIN_STO2_FEEDBACK_PORT GPIOG
#define PIN_STO2_FEEDBACK_PIN GPIO_PIN_10

/* ID_STRAP0: GPIO input on PE2, pin 1 */
#define PIN_ID_STRAP0_PORT GPIOE
#define PIN_ID_STRAP0_PIN GPIO_PIN_2

/* ID_STRAP1: GPIO input on PE3, pin 2 */
#define PIN_ID_STRAP1_PORT GPIOE
#define PIN_ID_STRAP1_PIN GPIO_PIN_3

/* ID_STRAP2: GPIO input on PE4, pin 3 */
#define PIN_ID_STRAP2_PORT GPIOE
#define PIN_ID_STRAP2_PIN GPIO_PIN_4

/* ID_STRAP3: GPIO input on PE5, pin 4 */
#define PIN_ID_STRAP3_PORT GPIOE
#define PIN_ID_STRAP3_PIN GPIO_PIN_5

/* LED_STATUS: GPIO output on PE1, pin 142 */
#define PIN_LED_STATUS_PORT GPIOE
#define PIN_LED_STATUS_PIN GPIO_PIN_1

/* LED_FAULT: GPIO output on PG6, pin 91 */
#define PIN_LED_FAULT_PORT GPIOG
#define PIN_LED_FAULT_PIN GPIO_PIN_6

/* LED_COMMS: GPIO output on PG7, pin 92 */
#define PIN_LED_COMMS_PORT GPIOG
#define PIN_LED_COMMS_PIN GPIO_PIN_7

/* BUTTON: GPIO input on PC13, pin 7 */
#define PIN_BUTTON_PORT GPIOC
#define PIN_BUTTON_PIN GPIO_PIN_13

#endif /* CPU1_BOARD_PINS_H */
